name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch: # this allows you to manually trigger a run with input parameters

jobs:
  build:
    uses: vegardit/haxe-reusable-workflows/.github/workflows/test-with-haxe.yml@v1
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        haxe:
        - nightly
        - latest  # latest stable release
        - 4.3.4
    with:
      runner-os: ${{ matrix.os }}
      haxe-version: ${{ matrix.haxe }}
      haxe-args: test.hxml
      haxe-libs: |
        buddy

      test-cpp: |
        enabled: true
        allow-failure: ${{ matrix.haxe == 'nightly' }}
      test-eval: |
        enabled: true
        allow-failure: ${{ matrix.haxe == 'nightly' }}
      test-hl: |
        enabled: true
        allow-failure: ${{ matrix.haxe == 'nightly' }}
      test-jvm: |
        enabled: true
        allow-failure: ${{ matrix.haxe == 'nightly' }}
      test-lua: |
        enabled: true
        allow-failure: true
      test-neko: |
        enabled: true
        allow-failure: ${{ matrix.haxe == 'nightly' }}
      test-node: |
        enabled: true
        allow-failure: ${{ matrix.haxe == 'nightly' }}
      test-php: |
        enabled: true
        allow-failure: true
      test-python: |
        enabled: true
        allow-failure: ${{ matrix.haxe == 'nightly' }}

      job-timeout-minutes: 30 # max. duration of the workflow, default is 60
      test-timeout-minutes: 5 # max. duration per target test, default is 10

      # bash script to be executed after compiler targets are installed and before target tests are executed
      # before-tests: |

      # bash script to be executed after tests were executed
      # after-tests: |
